<p><h1 class="headerLine">Over ons</h1></p>
<div class="leftColumn">

<p>
Trackprotect is ontwikkeld om artiesten in staat te stellen <b><i>onafhankelijk</i></b> hun auteursrecht te beschermen. 
</p>
<h3><b>RHOS Initiatives & Sound Framework</b></h3>
<p>
Trackprotect is een RHOS Initiative en maakt deel uit van Sound Framework. 
<p>
Sound Framework is de basis voor de nieuwe muziekindustrie waarbij transparantie, plezier en een nieuwe manier van geld verdienen met muziek centraal staan.
</p>
<p>
De komende maanden zullen er nog een aantal RHOS Initiatives aan het publiek worden gespresenteerd. 
<p>
De persoon achter Sound Framework is
<a href="http://www.rhosmovement.com/?lang=nl" target="_blank">Robin Hood of Sound (Rhos)</a> houdt zich bezig met het ontwerpen van innovatieve oplossingen voor de muziekindustrie.
Gerealiseerd door, en in samenwerking met, ondernemers met support van de crowd.
</p>
<p>
Na meer dan een eeuw van monopolies in de muziekindustrie is het tijd voor verandering.
</p>
<h3><b>Een gezonde muziekindustrie</b></h3>

<p>
Een gezonde muziekindustrie begint na creatie met registratie, en d&aacute;t doe je makkelijk &eacute;n betaalbaar met Trackprotect. 
</p>
<h3><b>Muziek mogelijk maken</b></h3>

<p>
Trackprotect is maar &eacute;&eacute;n van de stappen in de revolutie voor een nieuwe muziekindustrie. 
<p>
De lancering van Trackprotect heeft een reeks van gebeurtenissen in gang gezet die niet meer te stoppen zijn.
</p>
<p>
<i><b>Wees gewaarschuwd, we komen er aan!</b></i>
</p>
</div>