<p><h1 class="headerLine">About us</h1></p>
<div class="leftColumn">
<p>
Trackprotect is designed to enable artist to <b>independently</b> protect their music copyright in an easy and affordable way.  
</p>
<h3><b>RHOS Initiatives & Sound Framework</b></h3>
<p>
Track Protect is a RHOS Initiative and is part of Sound Framework.
</p>
;p:
Sound Framework is the basis for the new music industry where transparency, fun and a new way to monetize music stands central.
</p><br><br>
<p>
The person behind Sound Framework, <br><a href="http://www.rhosmovement.com/?lang=en" target="_blank">Robin Hood of Sound (Rhos)</a>, is engaged in designing innovative solutions for the music industry. 
Realized by, and in collaboration with, entrepreneurs with support from the crowd.
</p>
<p>
In the coming months a number of  RHOS Initiatives will be presented to the public.
</p>
<p>
After more than a century of musicindustry monopolies it's time for change.
</p>
<h3><b>A healthy music industry</b></h3>
<p>
A healthy starts by registration of the creation(s). Trackprotect helps you the do just that!
</p>

<h3><b>Enabling music</b></h3>
<p>
	Trackprotect is the first step in revolutionizing the music industry. It's launch has triggered a chain of events that can no longer be stopped.
</p>
<p>
	<b>Be advised, we're coming!</b>
</p>
</div>
