<div class="large-12 columns">
  <div class="row">
    <div class="large-6 push-6 columns">
      <div id="track">
        <i class="track"></i>
      </div>
      <div id="arrow-1" class="hide-for-small">
        <i class="arrow-1"></i>
      </div>
    </div>
    <div class="large-6 pull-6 columns right-align">
      <article>
        <header>
          <h2>JOUW EIGENDOM DELEN</h2>
        </header>
        <section>
          <p>Het succes van jouw muziek is verbonden met het delen ervan. Het internet is daarbij onmisbaar, maar vormt ook een probleem. Hoe deel je jouw muziek, zonder het zomaar weg te geven? Trackprotect helpt je daarbij.</p>
          <section>
        </article>
    </div>
  </div>
  <div class="row hide-for-small">
    <div class="large-12 columns">
      <div id="vault">
        <i class="vault"></i>
      </div>
      <div id="arrow-2" class="hide-for-small">
        <i class="arrow-2"></i>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="large-5 push-7 columns">
      <div id="lock">
        <i class="lock"></i>
      </div>
      <div id="arrow-3" class="hide-for-small">
        <i class="arrow-3"></i>
      </div>
    </div>
    <div class="large-7 pull-5 columns article-align">
      <article>
        <header>
          <h2>DIGITALE KLUIS EN CERTIFICAAT</h2>
        </header>
        <section>
          <p>Trackprotect helpt je te bewijzen op welk moment jouw muziek bestond. Dat helpt je te bewijzen vanaf wanneer jij auteursrecht hebt en dat jouw muziek van jou is. Deze informatie word verwerkt in een digitaal certificaat en veilig opgeslagen in jouw digitale kluis.</p>
          <section>
        </article>
    </div>
  </div>

  <div class="row">
    <div class="large-7 columns">
      <div id="network">
        <img src="images/infographic-network.png" alt="infographic network">
            </div>
      <div id="arrow-4" class="hide-for-small">
        <i class="arrow-4"></i>
      </div>
    </div>
    <div class="large-5 columns article-align">
      <article>
        <header>
          <h2>MUZIEK NETWERK TOOLS</h2>
        </header>
        <section>
          <p>Muziek maak je vaak niet alleen. Met Trackprotect nodig je eenvoudig de relaties uit waarmee je muziek maakt, of wilt maken! Nodig elkaar uit, bescherm samen tracks!</p>
          <section>
        </article>
    </div>
  </div>

  <div class="row">
    <div class="large-6 push-6 columns">
      <div id="share">
        <img src="images/infographic-share.png" alt="infographic share">
                        </div>
      <div id="arrow-5" class="hide-for-small">
        <i class="arrow-5"></i>
      </div>
    </div>
    <div class="large-6 pull-6 columns article-align">
      <article>
        <header>
          <h2>SOCIAL MEDIA TOOLS</h2>
        </header>
        <section>
          <p>Al jouw beschermde tracks met één druk op de knop automatisch en veilig delen via Soundcloud, Twitter en Facebook? Het kan, en Trackprotect helpt je daarbij!</p>
          <section>
                    </article>

    </div>

  </div>

  <div class="row">
    <div class="large-7 push-5 columns article-align">
      <article>
        <header>
          <h2>AGENCIES EN MANAGEMENT</h2>
        </header>
        <section>
          <p>Omdat jij zoveel mogelijk bezig wilt zijn met het maken van muziek heeft Trackprotect in het managed plan management tools voor jouw management ontwikkelt. Hiermee kunnnen ze jouw Trackprotect account voor je beheren.</p>
          <section>
                    </article>
    </div>
    <div class="large-5 pull-7 columns">
      <a class="button-try button extra-large" href="/Account/Register.aspx">PROBEER HET NU</a>

    </div>
  </div>
</div>

