<div class="large-7 columns">
    <h1>
        <span class="underline">JOUW</span> TRACKS<br />
        &nbsp;&nbsp;&nbsp;&nbsp;ZIJN VAN <span class="underline">JOU</span>. <span class="orange">
            TOCH?</span> <span class="arrow-right hide-for-small"></span>
    </h1>
    <div class="flex-video show-for-small">
        <iframe width="364" height="205" src="http://www.youtube.com/embed/hWnAqFyaQ5s" frameborder="0"
            allowfullscreen></iframe>
    </div>
    <p>
        bescherm, deel &eacute;n cre&euml;er waarde<br />
        met jouw tracks via trackprotect.</p>
    <div class="button-row row collapse">
        <div class="large-7 columns">
            <a class="button extra-large" href="Account/Register.aspx">MELD JE GRATIS AAN</a>
        </div>
        <div class="large-5 columns">
            <a class="button secondary button-with-arrow extra-large scroll" href="#infographic">VIND UIT HOE</a>
            <span class="arrow-down hide-for-small"></span>
        </div>
    </div>
    <ul class="inline-list">
        <li><a href="http://www.facebook.com/trackprotect" target="_blank"><i class="icon-facebook-c"></i></a></li>
        <li><a href="http://www.twitter.com/trackprotect" target="_blank"><i class="icon-twitter-c"></i></a></li>
        <li><a href="http://www.soundcloud.com/trackprotect" target="_blank"><i class="icon-soundcloud-c"></i></a></li>
    </ul>
</div>
<div class="large-5 columns">
    <div class="flex-video hide-for-small">
        <iframe width="364" height="205" src="http://www.youtube.com/embed/hWnAqFyaQ5s" frameborder="0">
        </iframe>
    </div>
    <div class="twitter-widget">
        <h2>
            ACTUEEL</h2>
        <ul>
            <li>
                <div class="row">
                    <div class="large-3 columns">
                        <img src="http://placehold.it/60x60" alt="" />
                    </div>
                    <div class="large-9 columns">
                        <p>
                            RHOS gooit Buma/Stemra omver in rechtzaak!...</p>
                        <p class="date">
                            23 mei 2013</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="row">
                    <div class="large-3 columns">
                        <img src="http://placehold.it/60x60" alt="" />
                    </div>
                    <div class="large-9 columns">
                        <p>
                            RHOS gooit Buma/Stemra omver in rechtzaak!...</p>
                        <p class="date">
                            23 mei 2013</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="row">
                    <div class="large-3 columns">
                        <img src="http://placehold.it/60x60" alt="" />
                    </div>
                    <div class="large-9 columns">
                        <p>
                            RHOS gooit Buma/Stemra omver in rechtzaak!...</p>
                        <p class="date">
                            23 mei 2013</p>
                    </div>
                </div>
            </li>
        </ul>
        <div class="row">
            <div class="large-3 large-offset-9 columns">
                <a class="button small border" href="#">MEER...</a>
            </div>
        </div>
    </div>
</div>
