<div class="row">
<div class="large-12 columns">
    <div class="section-title center">
        <h1>
            DE VOORDELEN</h1>
    </div>
</div>
</div>
<div class="row">
<div class="large-4 columns">
    <div id="benefit-protect">
    </div>
    <h2>
        Auteursrecht simpel en betaalbaar beschermd</h2>
</div>
<div class="large-4 columns">
    <div id="benefit-cloud">
    </div>
    <h2>
      AL JOUW PRODUCTIES IN ÉÉN ONLINE ARCHIEF</h2>
</div>
<div class="large-4 columns">
    <div id="benefit-social">
    </div>
    <h2>
      GRATIS SOCIAL MEDIA EN NETWERK TOOLS</h2>
</div>
</div>