<h3>
  RHOS Initiatives & Sound Framework
</h3>
<p>
  Trackprotect is een RHOS Initiative en maakt deel uit van Sound Framework.
</p>
<p>
  Sound Framework is de basis voor de nieuwe muziekindustrie waarbij transparantie,
  plezier en een nieuwe manier van geld verdienen met muziek centraal staan.
</p>
<p>
  De komende maanden zullen er nog een aantal RHOS Initiatives aan het publiek worden
  gespresenteerd.
</p>
<h3>
  Een gezonde muziekindustrie
</h3>
<p>
  Een gezonde muziekindustrie begint na creatie met registratie, en dát doe je makkelijk
  én betaalbaar met Trackprotect.
</p>
<h3>
  Muziek mogelijk maken
</h3>
<p>
  Trackprotect is maar één van de stappen in de revolutie voor een nieuwe muziekindustrie.
</p>
<p>
  De lancering van Trackprotect heeft een reeks van gebeurtenissen in gang gezet die
  niet meer te stoppen zijn.
</p>
<p>
  <em>Wees gewaarschuwd, we komen er aan!</em>
</p>
