
<div class="leftColumn">
<p>
	Heb je een vraag over het gebruik van Trackprotect? Wij hebben er hier een aantal veelgestelde vragen alvast voor jou onder elkaar gezet. 
	Staat het antwoord op jouw vraag er niet bij? <br>Laat het ons weten! Stuur een email met jouw vraag aan <a href="mailto:support@trackprotect.com">support@trackprotect.com</a>.
</p>
<h2>F.A.Q's - Top 10</h2>
<ul class="faqlist">
	<li>
		<span class="question">1. Waarom zou ik mijn tracks via Trackprotect beschermen?</span>
		<span class="answer">Als jij een track maakt heb je automatisch het auteursrecht. Het is alleen vaak moeilijk te bewijzen wanneer je iets hebt gemaakt. Trackprotect helpt jou bewijzen wanneer jouw track al bestond. Als dat vastgesteld kan worden is er in ieder geval sprake van auteursrecht vanaf dat moment.</span>
	</li>
	<li>
		<span class="question">2. Kost het geld om een account aan te maken? <br/> </span>
		<span class="answer">Nee, een account bij Trackprotect is kostenloos. Pas wanneer je tracks vastlegt heb je credits nodig; die zijn verkrijgbaar via de website.</span>
	</li>
	<li>
		<span class="question">3. Je hebt toch al Buma Stemra en Sena, waarom n&oacute;g een dienst?</span>
		<span class="answer">Buma Stemra en de Sena zijn er om collectief auteursrechtengelden te innen en te verdelen. Zij gaan niet over de bescherming van jouw werk.</span>
	</li>
	<li>
		<span class="question">4. Is Trackprotect de nieuwe, of tegenhanger van, Buma Stemra of Sena?</span>
		<span class="answer">Nee, Trackprotect levert een dienst die je helpt jouw auteursrecht te bewijzen. Trackprotect is niet betrokken bij het innen of verdelen van jouw auteursgelden. Trackprotect is een toevoeging voor auteursrechthebbenden in het geval dat anderen zonder toestemming gebruik maken van hun tracks.
		</span>
	</li>
	<li>
		<span class="question">5. Wat is een ISRC code, en waarom moet ik die hebben?</span>
		<span class="answer">ISRC code staat voor "International Standard Recording Code", en is bedoeld als een soort 'kentekenregistratie' voor tracks. De Sena geeft de kentekens (ISRC codes) uit. Het is daarom belangrijk om je te registreren bij de Sena, dan deel je mee in de verdeling van de collectief ge&iuml;nde auteursgelden. </span>
	</li>
	<li>
		<span class="question">6. Wat voor juridische waarde heeft de registratie van mijn tracks?</span>
		<span class="answer">De Nederlandse wetgeving kent geen digitale certificaten. De registratie van jouw tracks levert ondersteunend bewijs op. Mocht je in een juridisch conflict belanden dan ondersteunt het jouw claim dat een track van jou is, en dat jij het auteursrecht hebt. Een rechter zal dan in veel gevallen kijken wat iemand heeft gedaan om zijn recht te beschermen. Jouw track registreren laat zien dat jij je daar voor ingespannen hebt. Dwingend bewijs (onomstotelijk bewijs) kan je alleen krijgen door middel van een depot akte bij de Notaris.</span>
	</li>
	<li>
		<span class="question">7. Is het verplicht om mijn accountgegevens ondertekend in te leveren?</span>
		<span class="answer">Nee, dat is niet verplicht, maar het draagt wel bij aan het gewicht van jouw bewijs. Dus hoe vollediger jij jouw account registratie doet, hoe krachtiger jouw bewijs.</span>
	</li>
	<li>
		<span class="question">8. Hoe kan het dat het beschermen van mijn track bij Trackprotect w&eacute;l betaalbaar is?</span>
		<span class="answer">&Eacute;&eacute;n van de redenen is dat Trackprotect jouw track voor &eacute;&eacute;n jaar vastlegt. In veel gevallen kan dat alleen vanaf 5 jaar. Een andere reden is omdat Trackprotect een RHOS Initiative is, op basis van het Robin Hood of Sound gedachtengoed. Een belangrijk criterium van het RHOS gedachtengoed is dat het voor iedereen toegankelijk moet zijn, dus ook qua prijsstelling.</span>
	</li>
	<li>
		<span class="question">9. Waar kan ik terecht als iemand zonder mijn toestemming mijn track gebruikt?</span>
		<span class="answer">Trackprotect heeft verschillende juridische partners waarmee afspraken zijn gemaakt om Trackprotect gebruikers betaalbaar bij te staan in het geval van een conflict.
Deze partners hebben jarenlange ervaring op het gebied van auteursrecht en steunen ook het RHOS gedachtengoed. Heb je een probleem met &eacute;&eacute;n van jouw tracks? Laat het ons weten, dan brengen we je in contact met de juiste partij! <a href="mailto:support@trackprotect.com?SUBJECT=Ik heb juridische hulp nodig!">support@trackprotect.com</a></span>
	</li>
	<li>
		<span class="question">10. Wat is een meewerkende artiest?</span>
		<span class="answer">Een meewerkende artiest is iemand met wie je samen een track hebt gemaakt; bijvoorbeeld een medecomponist, achtergrondzangeres, een drummer of gitarist.</span>
	</li>
</ul>
<h2>Collectief tracks beschermen : Het Bulk Plan</h2>
<ul class="faqlist">
	<li>
		<span class="question">Ik vertegenwoordig meerdere artiesten; kan ik ook collectief registreren?</span>
		<span class="answer">Ja, wij hebben een managementpaneel voor partijen die voor meerdere artiesten registraties uitvoeren. Het managementpaneel is alleen beschikbaar in combinatie met het bulk plan.</span>
	</li>
	<li>
		<span class="question">Wat zijn de voordelen van het bulk plan?</span>
		<span class="answer">Er zijn twee belangrijke redenen om voor een "Bulk Plan" te kiezen:<ol><li>Je kan vanuit &eacute;&eacute;n account voor meerdere gebruikers onder hun account track registreren</li><li>Je koopt bulk je credits in en daardoor zijn ze nog voordeliger.</li></ol>
</span>
	</li>
	<li>
		<span class="question">Komt het certificaat dan wel op mijn naam?</span>
		<span class="answer">Ja, het managementpaneel is een aparte gebruiker die voor jou je track kan registreren; het certificaat komt daardoor gewoon op jouw naam en er word ook bijgehouden wie de registratie heeft gedaan.</span>
	</li>
	<li>
		<span class="question">Kan iemand iets wijzigen in mijn registraties?</span>
		<span class="answer">Nee. Als een registratie eenmaal is gedaan ligt deze vast. Dat heeft onder andere met het digitale certificaat te maken, en het behoud van de bewijskracht in geval van een conflict. Als er achteraf iets zou kunnen worden gewijzigd dan ontkracht dat je bewijs.</span>
	</li>
</ul>
<h2>Sociale betrokkenheid</h2>
<ul class="faqlist">
	<li>
		<span class="question">Draagt Trackprotect iets bij aan de samenleving?</span>
		<span class="answer">Ja, Trackprotect maakt deel uit van een groter goed, het RHOS Movement Music Eco Framework, dat streeft naar een duurzame en voor iedereen toegankelijke muziekindustrie.</span>
	</li>
	<li>
		<span class="question">Wat heeft Trackprotect met RHOS Movement te maken?</span>
		<span class="answer">Trackprotect is een RHOS Initiative. Dat zijn Robin Hood of Sound concepten mogelijk gemaakt door, en in samenwerking met, ondernemers met support van de crowd.</span>
	</li>
	<li>
		<span class="question">Wat heeft Trackprotect met Stichting Sustain Sound te maken?</span>
		<span class="answer">Stichting Sustain Sound is opgericht door mensen uit de samenleving die het RHOS gedachtengoed een warm hart toedragen. De stichting heeft bijgedragen aan de ontwikkeling van Trackprotect.</span>
	</li>
	<li>
		<span class="question">Ik vind Trackprotect en RHOS Movement een goed initiatief, hoe kan ik bijdragen?</span>
		<span class="answer">RHOS Movement is bezig met een grondige renovatie van de muziekindustrie, en dat is nogal wat. We kunnen dus alle hulp gebruiken! Stuur een mailtje aan <a href="mailto:rhos@rhosmovement.com">rhos@rhosmovement.com</a> dan krijg je zo spoedig mogelijk antwoord van Robin Hood of Sound.</span>
	</li>
</ul>
<h2>Trackprotect en het onderwijs</h2>
<ul class="faqlist">
	<li>
		<span class="question">Trackprotect en het onderwijs?</span>
		<span class="answer">Trackprotect draagt ook haar steentje bij aan een gezonde muziekindustrie. Dat doet het bedrijf door credits ter waarde van &euro; 100.000,- beschikbaar te stellen en te verdelen onder alle muziekstudenten in Nederland. <a href="/promo.aspx">Lees meer ...</a></span>
	</li>
	<li>
		<span class="question">Ik volg een muziekopleiding; hoe word ik Trackprotect ambassadeur?</span>
		<span class="answer">Iedereen kan zich aanmelden. De enige criteria zijn dat je een muziekopleiding volgt, en de eerste bent van jouw school die zich aanmeldt. <a href="/promo.aspx">Lees meer ...</a></span>
	</li>
</ul>
<h2>Algemene vragen over gebruik en werking Trackprotect</h2>
<ul class="faqlist">	
	<li>
		<span class="question">Voor hoe lang is mijn track beschermd?</span>
		<span class="answer">Je beschermt jou track gedurende 1 jaar, voor de prijs van 1 credit.</span>
	</li>
	<li>
		<span class="question">Hoe kan ik credits kopen, en gebeurt mijn online betaling wel veilig?</span>
		<span class="answer">De betalingen op de website worden 100% veilig afgehandeld door payment service provider <a href="http://www.icepay.nl" target="_blank">Icepay</a>.</span>
	</li>
	<li>
		<span class="question">Ik heb teksten en bladmuziek, kan ik dan ook Trackprotect gebruiken?</span>
		<span class="answer">Je kan bij iedere track die word beschermd ook de bladmuziek en songteksten uploaden. Die worden dan meegenomen in de registratie en versterken jouw bewijskracht.</span>
	</li>
	<li>
		<span class="question">Kan je de geregistreerde tracks via Trackprotect beluisteren?</span>
		<span class="answer">Ja, je kan jouw beschermde tracks beluisteren, maar alleen wanneer je pro account credits hebt gekocht. De player functie blijft actief zo lang als jouw pro account credits geldig zijn: een heel jaar!.</span>
	</li>
	<li>
		<span class="question">Wat moet ik doen als ik wijzigingen aanbreng in mijn track?</span>
		<span class="answer">Als er iets wijzigt in een track moet je deze opnieuw registreren. De waarde van de Trackprotect bescherming zit hem in het vastleggen van de staat van de track op een bepaald moment. Wanneer er wijzigingen worden aangebracht moeten deze opnieuw worden vastgelegd.</span>
	</li>
	<li>
		<span class="question">Hoe groot mag het muziekbestand dat geregistreerd word zijn?</span>
		<span class="answer">Maximaal 10 megabyte per upload.</span>
	</li>
	<li>
		<span class="question">Kan ik meerdere tracks in 1 keer vastleggen?</span>
		<span class="answer">Nee, iedere registratie moet per track worden uitgevoerd. Je kan uiteraard wel meerdere tracks vastleggen gedurende &eacute;&eacute;n sessie.</span>
	</li>
	<li>
		<span class="question">Kan ik mijn track in 1 keer voor meerdere termijnen vastleggen?</span>
		<span class="answer">Nee, je legt op dit moment 1 track voor 1 jaar vast en het Trackprotect systeem stuurt je ruim van tevoren een melding wanneer de termijn van 1 jaar afloopt.</span>
	</li>
	<li>
		<span class="question">Wat is een meewerkende artiest?</span>
		<span class="answer">Een meewerkende artiest is iemand met wie je samen een track hebt gemaakt; bijvoorbeeld een medecomponist, achtergrondzangeres, een drummer of gitarist.</span>
	</li>
	<li>
		<span class="question">Ik kan geen meewerkende artiesten toevoegen tijdens de registratie.</span>
		<span class="answer">Om meewerkende artiesten toe te voegen aan een track moet je eerst een relatie met een artiest hebben.</span>
	</li>
	<li>
		<span class="question">Hoe voeg ik andere artiesten als relatie toe aan mijn account?</span>
		<span class="answer">Om een relatie te leggen met een artiest ga je naar het controlepaneel, klik je op relaties en vul je daar het emailadres van de artiest die je wilt toevoegen in. De persoon van het emailadres krijgt van Trackprotect een uitnodiging. In deze uitnodiging staat een link waarmee hij of zij word gevraagd de uitnodiging te accepteren. Als die persoon al een Trackprotect gebruiker is herkent het Trackprotect systeem deze persoon als gebruiker en word er een relatie tussen jullie gelegd. Als de ontvanger nog geen Trackprotect gebruiker is dan word hij gevraagd te registreren waarna er een relatie tussen jou en de andere gebruiker wordt gelegd en daardoor wordt jullie relatie  nu in het controlepaneel zichtbaar.</span>
	</li>	
	<li>
		<span class="question">Ik heb samen met iemand een track gemaakt, wie heeft dan het auteursrecht?</span>
		<span class="answer">Als je samen een track maakt heb je samen auteursrecht. Als je jullie track registreert dan is diegene onder wiens account de track word geregistreerd hoofd registrant, de ander word aangemerkt als meewerkende artiest. Het maakt niet uit wie de hoofdregistrant is.</span>
	</li>	
	<li>
		<span class="question">Ik heb een email ontvangen met een uitnodiging, wat moet ik daarmee? </span>
		<span class="answer">Als je de persoon die je de uitnodiging heeft gestuurd kent, en je wilt deze persoon toevoegen aan je relaties in Trackprotect klik dan op accepteer. Als je dat niet wilt, dan hoef je niets te doen.</span>
	</li>
	<li>
		<span class="question">Kunnen anderen mijn relaties tussen mij en andere gebruikers zien?</span>
		<span class="answer">Nee, dat is alleen voor jou en de relatie zichtbaar.</span>
	</li>
</ul>
<h2>Administratief</h2>
<ul class="faqlist">	
	<li>
		<span class="question">Blijven mijn credits voor altijd geldig?</span>
		<span class="answer">Nee, credits blijven 1 jaar geldig. Gedurende dit jaar kunnen de credits worden ingezet om tracks te beschermen. Op het moment dat een credit worden gebruikt biedt deze bescherming voor 1 jaar.</span>
	</li>
	<li>
		<span class="question">Blijft mijn account altijd bestaan?</span>
		<span class="answer">In principe wel, het is afhankelijk van de activiteit van jouw account. Word je bijvoorbeeld genoemd als meewerkende artiest in andere registraties dan blijft jouw account bestaan. Als er geen actieve geregistreerde tracks meer zijn en er is ook geen relatie meer tot andere tracks dan word jouw account na 3 maanden verwijderd. Je ontvangt natuurlijk wel ruim op tijd een herinnering per email van het Trackprotect systeem dat jouw account zal worden gesloten.</span>
	</li>
	<li>
		<span class="question">Wat gebeurt er als de registratie van mijn track verloopt?</span>
		<span class="answer">Voordat de registratietermijn verloopt krijg je per email een herinnering dat dit het geval is, en om welke tracks het gaat. Jij hebt dan de keuze of je de registratie met 1 jaar wil verlengen.</span>
	</li>
	<li>
		<span class="question">Ik heb een email ontvangen over credits en registratie termijn</span>
		<span class="answer">Voordat geldigheidstermijn van jouw credits verlopen krijg je per email een herinnering. Je kan dan kiezen om voordat de credits verlopen nog een aantal tracks te beschermen.</span>
	</li>
	<li>
		<span class="question">Waarom verlopen credtis?</span>
		<span class="answer">Toen het Trackprotect systeem werd ontworpen hadden we twee keuzes, maandelijkse kosten berekenen of het verlopen van credits. We houden onze systemen graag up to date en schoon, niemand heeft iets aan 3 jaar oude accounts zonder beschermde tracks. Dit soort accounts zijn niet in het belang van Trackprotect in het Musc Eco Framework, data moet courant en relevant zijn voor het framework.</span>
	</li>
	<li>
		<span class="question">Ik heb betaald, en mijn credits zijn niet aan mijn account toegevoegd</span>
		<span class="answer">Neem in dit geval zo spoedig mogelijk contact op met <a href="mailto:support@trackprotect.com">support@trackprotect.com</a></span>
	</li>
</ul>
<h2>Privacy</h2>
<ul class="faqlist">	
	<li>
		<span class="question">Deelt Trackprotect mijn gegevens ook met andere bedrijven?</span>
		<span class="answer">Nee, Trackprotect zal nooit zonder jouw toestemming je gegevens delen met anderen.</span>
	</li>
	<li>
		<span class="question">Kunnen anderen bij mijn tracks of gegevens?</span>
		<span class="answer">Nee, absoluut niet.</span>
	</li>
	<li>
		<span class="question">Wat gebeurt er met al mijn gegevens als ik mijn account opzeg?</span>
		<span class="answer">Als je jouw Trackprotect account opzegt worden alle gegevens uit het systeem gewist, inclusief geregistreerde tracks.</span>
	</li>
</ul>
<h2>Data en veiligheid</h2>
<ul class="faqlist">	
	<li>
		<span class="question">Waar worden mijn tracks opgeslagen?</span>
		<span class="answer">De tracks en digitale certificaten worden opgeslagen op de beveiligde servers van Trackprotect.</span>
	</li>
	<li>
		<span class="question">Hoe zit het met de veiligheid van de Trackprotect servers?</span>
		<span class="answer">De Trackprotect servers zijn ondergebracht in een beveiligd datacenter. De data word goed gebackupped en de servers worden beheerd door gekwalificeerde systeembeheerders.</span>
	</li>
</ul>
<!--
<h2></h2>
<ul class="faqlist">	

</ul>
-->
</div>