<div class="section-title center">
  <h1>
    F.A.Q
  </h1>
</div>
<!-- We will show the top 10 Questions here -->
<div class="row">
  <div class="large-6 columns">
    <ul class="no-style">
      <li>
        <h3>
          <span class="question">1. Waarom zou ik mijn tracks via Trackprotect beschermen?</span>
        </h3>
        <p>
          <span class="answer">
            Waarom zou ik mijn tracks via Trackprotect beschermen? Als jij een track maakt heb
            je automatisch het auteursrecht. Het is alleen vaak moeilijk te bewijzen wanneer
            je iets hebt gemaakt. Trackprotect helpt jou bewijzen wanneer jouw track al bestond.
            Als dat vastgesteld kan worden is er in ieder geval sprake van auteursrecht vanaf
            dat moment.
          </span>
        </p>
      </li>
      <li>
        <h3>
          <span class="question">2. Kost het geld om een account aan te maken?</span>
        </h3>
        <p>
          <span class="answer">Nee, een account bij Trackprotect is kostenloos. Pas wanneer je tracks vastlegt heb je credits nodig; die zijn verkrijgbaar via de website.</span>
        </p>
      </li>
      <li>
        <h3>
          <span class="question">3. Je hebt toch al Buma Stemra en Sena, waarom n&oacute;g een dienst?</span>
        </h3>
        <p>
          <span class="answer">Buma Stemra en de Sena zijn er om collectief auteursrechtengelden te innen en te verdelen. Zij gaan niet over de bescherming van jouw werk.</span>
        </p>
      </li>
      <li>
        <h3>
          <span class="question">4. Is Trackprotect de nieuwe, of tegenhanger van, Buma Stemra of Sena?</span>
        </h3>
        <p>
          <span class="answer">
            Nee, Trackprotect levert een dienst die je helpt jouw auteursrecht te bewijzen. Trackprotect is niet betrokken bij het innen of verdelen van jouw auteursgelden. Trackprotect is een toevoeging voor auteursrechthebbenden in het geval dat anderen zonder toestemming gebruik maken van hun tracks.
          </span>
        </p>
      </li>
      <li>
        <h3>
          <span class="question">5. Wat is een ISRC code, en waarom moet ik die hebben?</span>
        </h3>
        <p>
          <span class="answer">ISRC code staat voor "International Standard Recording Code", en is bedoeld als een soort 'kentekenregistratie' voor tracks. De Sena geeft de kentekens (ISRC codes) uit. Het is daarom belangrijk om je te registreren bij de Sena, dan deel je mee in de verdeling van de collectief ge&iuml;nde auteursgelden. </span>
        </p>
      </li>
    </ul>
  </div>
  <div class="large-6 columns">
    <ul class="no-style">
      <li>
        <h3>
          <span class="question">6. Wat voor juridische waarde heeft de registratie van mijn tracks?</span>
        </h3>
        <p>
          <span class="answer">De Nederlandse wetgeving kent geen digitale certificaten. De registratie van jouw tracks levert ondersteunend bewijs op. Mocht je in een juridisch conflict belanden dan ondersteunt het jouw claim dat een track van jou is, en dat jij het auteursrecht hebt. Een rechter zal dan in veel gevallen kijken wat iemand heeft gedaan om zijn recht te beschermen. Jouw track registreren laat zien dat jij je daar voor ingespannen hebt. Dwingend bewijs (onomstotelijk bewijs) kan je alleen krijgen door middel van een depot akte bij de Notaris.</span>
        </p>
      </li>
      <li>
        <h3>
          <span class="question">7. Is het verplicht om mijn accountgegevens ondertekend in te leveren?</span>
        </h3>
        <p>
          <span class="answer">Nee, dat is niet verplicht, maar het draagt wel bij aan het gewicht van jouw bewijs. Dus hoe vollediger jij jouw account registratie doet, hoe krachtiger jouw bewijs.</span>
        </p>
      </li>
      <li>
        <h3>
          <span class="question">8. Hoe kan het dat het beschermen van mijn track bij Trackprotect w&eacute;l betaalbaar is?</span>
        </h3>
        <p>
          <span class="answer">&Eacute;&eacute;n van de redenen is dat Trackprotect jouw track voor &eacute;&eacute;n jaar vastlegt. In veel gevallen kan dat alleen vanaf 5 jaar. Een andere reden is omdat Trackprotect een RHOS Initiative is, op basis van het Robin Hood of Sound gedachtengoed. Een belangrijk criterium van het RHOS gedachtengoed is dat het voor iedereen toegankelijk moet zijn, dus ook qua prijsstelling.</span>
        </p>
      </li>
      <li>
        <h3>
          <span class="question">9. Waar kan ik terecht als iemand zonder mijn toestemming mijn track gebruikt?</span>
        </h3>
        <p>
          <span class="answer">
            Trackprotect heeft verschillende juridische partners waarmee afspraken zijn gemaakt om Trackprotect gebruikers betaalbaar bij te staan in het geval van een conflict.
            Deze partners hebben jarenlange ervaring op het gebied van auteursrecht en steunen ook het RHOS gedachtengoed. Heb je een probleem met &eacute;&eacute;n van jouw tracks? Laat het ons weten, dan brengen we je in contact met de juiste partij! <a href="mailto:support@trackprotect.com?SUBJECT=Ik heb juridische hulp nodig!">support@trackprotect.com</a>
          </span>
        </p>
      </li>
      <li>
        <h3>
          <span class="question">10. Wat is een meewerkende artiest?</span>
        </h3>
        <p>
          <span class="answer">Een meewerkende artiest is iemand met wie je samen een track hebt gemaakt; bijvoorbeeld een medecomponist, achtergrondzangeres, een drummer of gitarist.</span>
        </p>
      </li>
    </ul>
  </div>
</div>
<!-- End the top 10 Questions -->
<div class="row">
  <div class="small-12 columns">
    <a class="right" href="FAQ.aspx">Click to see all &lt;&lt;</a>
  </div>
</div>