

			 <div class="row">
                <!-- Full Width -->
                <!-- Main Content -->
                <div class="small-12 columns">
                    <div class="section-title small to-left show-for-small">
                        <h1>
                          Voltooi jouw account info
                        </h1>
                    </div>
                    <div class="row">
                        <div class="small-12 large-10 large-centered columns">
                            <h1 class="orange">
                                lieve VarFirstName
                                </h1>
                            <p> Bedankt voor het registreren. Ja, dit is een uitleg waarom we hebben je nodig om dit te doen. We weten dat het een hoop werk, maar het is in uw eigen belang.</p>
                            <p>Om het u zo gemakkelijk mogelijk te maken, hebben we opgedeeld dingen in 4 secties:</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="small-12 large-6 large-offset-1">
                            <h2 class="step">
                                <a href="Member/ProfileInfo.aspx"><span class="number-circle">1</span>INFO<span class="explain">Maak uw<br>
                                    persoonlijke informatie</span></a></h2>
                            <div id="dotted-arrow-1" class="hide-for-small">
                                <i class="dotted-arrow-1"></i>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="small-12 large-6 large-offset-6">
                            <h2 class="step">
                                <a href="Member/ProfileReg.aspx"><span class="number-circle">2</span>Registratie<span class="explain">Voer uw<br>
                                     bestaande gegevens</span></a></h2>
                            <div id="dotted-arrow-2" class="hide-for-small">
                                <i class="dotted-arrow-2"></i>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="small-12 large-6 large-offset-2">
                            <h2 class="step">
                                <a href="Member/Profile.aspx"><span class="number-circle">3</span>connect<span class="explain">uw sociale<br>
                                    media netwerken</span></a></h2>
                            <div id="dotted-arrow-3" class="hide-for-small">
                                <i class="dotted-arrow-3"></i>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="small-12 large-6 large-offset-5">
                            <h2 class="step">
								<a href="Member/ProfilePrint.aspx"><span class="number-circle">4</span>verify<span class="explain">compleet rekening<br>verificatie</span></a></h2>
                        </div>
                    </div>
                    <!--<div class="profile-actions row">
                        <div class="small-12 large-6 columns">
                            <a class="button large border right" href="Member/MemberHome.aspx">NO THANKS, Onthoud mij</a>
                        </div>
                        <div class="small-12 large-6 columns">
                            <a class="button large border highlight" href="Member/ProfileInfo.aspx"> COMPLEET uw profiel nu</a>
                        </div>
                    </div>-->
                  
                  <div class="profile-actions row">

                    <div class="small-12 large-6 columns">
                      <a class="button large border right"  href="Member/ProfileInfo.aspx">COMPLEET uw profiel nu</a>
                    </div>

                    <div class="small-12 large-6 columns">
                      <a class="button large border highlight"  href="Member/MemberHome.aspx">NO THANKS, Onthoud mij</a>
                    </div>
                  </div>
                </div>
                <!-- End Main Content -->
            </div>
