<p><h1 class="headerLine">Hoe het werkt</h1></p>
<div class="leftColumn">
<!--<img src="images/guitarguy.jpg" width="100%" align="right">-->
<p>
	Trackprotect is een dienst voor muziek auteursrechtbescherming. Auteursrecht ontstaat automatisch wanneer je jouw muziek maakt, daar hoef je niets voor te doen.
	De uitdaging zit hem in het bewijzen wanneer jouw muziek al bestond. Trackprotect helpt je daarbij.
</p>
<h3><b>Een digitale kluis en certificaat</b></h3>
<p>	
	Trackprotect helpt je, op basis van een digitaal certificaat, te bewijzen op welk moment jouw werk al bestond.  
	Dat helpt je te bewijzen wanneer jouw auteursrecht is ontstaan en dat het jouw werk is. Deze gegevens worden veilig opgeslagen in een digitale kluis.
</p>
<p>
<h3><b>Muziek netwerk tools</b></h3>
Muziek maak je vaak niet alleen. Beheer met Trackprotect eenvoudig de relaties waarmee je hebt samengewerkt &oacute;f samen wilt werken!
Nodig elkaar uit en bescherm samen tracks!
</p>
<p>
<h3><b>Social Media Marketing tools</b></h3>
Trackprotect heeft een aantal social media tools ontwikkeld die met &eacute;&eacute;n druk op de knop jouw track gepubliceert naar Soundcloud, Facebook &eacute;n Twitter!
</p>
<p>
<h3><b>Tracks beschermen</b></h3>
<p>
Om je tracks te beschermen heb je credits nodig. Het beschermen van een track kost 1 credit voor 1 jaar. Gedurende dit jaar wordt de track veilig bewaard in jouw account. 
</p>
<p>
<h3><b>De voordelen op een rijtje:</b></h3><br>
<strong>
	<ol>
		<li>Jouw auteursrecht snel eenvoudig &eacute;n betaalbaar beschermd</li>
		<li>Jouw producties overzichtelijk en veilig in &eacute;&eacute;n online archief</li>
		<li>Gratis social media en netwerk tools</li>
	</ol>
	</strong>
</p><br>

<h3><b>Meld je aan</b></h3>
<p>
	Trackprotect is effectief, makkelijk in gebruik en kosteneffici&euml;nt.
	Een account aanmaken is gratis!
</p>

<p>
<strong><i>	Zo, nu weet je hoe het werkt... <br>Waar wacht je nog op?</strong></i>
</p>
<p><br>
	<!--<a href="http://www.trackprotect.com/Account/Register.aspx"><img src="/images/btn_signup.png"></a>-->
  <a href="/Account/Register.aspx">
    <img src="/images/btn_signup.png">
  </a>
</p>
</div>