<p>
	<h1 class="headerLine">RHOS: Enabling music.</h1>
</p>
<div class="leftColumn">
<p>

Trackprotect investeert in samenwerking met stichting Sustain Sound in de muziekindustrie van morgen en stelt daarom 2500 pro accounts t.w.v. &euro; 125.000,- beschikbaar.
<p>
<h3><strong>Wist je dat?</h3></strong>
De 2500 pro accounts staan voor 5 keer 500 accounts en dat de vijf symbool staat voor de 5% mensen in Nederland die nog wel betalen voor muziek. 

<br><br>Het is bedoelt als bijdrage om muzikanten bewust te maken van het belang om hun werk te beschermen. Dat is het begin van een gezonde muziekindustrie. <br><br>

<br> <br>  
<h3><strong>Claim jouw pro plan coupon!</h3></strong>
Volg jij een (muziek)opleiding? 

Claim dan nu jouw coupon code om zo kosteloos jouw eerste 40 creaties vast te leggen! <br><br> </p><A HREF="mailto:rhos@rhosmovement.com?SUBJECT=Ik wil mijn coupon code!">Meld je dan nu hier aan!</A> 
</p>
<p>
<h3><strong>Win een dag in een professionele studio!</h3></strong>
<p>
Zie jij ook het belang in van het beschermen van muziek en wil je helpen?
</p>
<p>
Meld je dan nu aan en word Trackprotect ambassadeur en maak kans op een volledig verzorgd studio arrangement in een professionele studio.
</p>
<A HREF="mailto:rhos@rhosmovement.com?SUBJECT=Maak me ambassadeur!">Aanmelden doe je hier!</A></p>

</div>