/*
-- Query: SELECT * FROM `rhosmove_tpdb`.`productdesc`
LIMIT 0, 1000

-- Date: 2012-03-13 13:33
*/
INSERT INTO `productdesc` (productdesc_id,product_id,locale,title,description) VALUES (1,1,'en-US','<h1 class="productLabel">Thank you for choosing the <span style="color: orange;">TrackProtect Starter-plan</span></h1>','<h1>What''s in it for you</h1><p>With this package you buy 5 registration credits.</p><p>This means you can register 5 tracks for a period of one year and you''ll be able to download a certificate generated specifically for you and your track as proof of registration thus giving you undisputable copyrights.');
INSERT INTO `productdesc` (productdesc_id,product_id,locale,title,description) VALUES (2,1,'nl-NL','<h1 class="productLabel">Thank you for choosing the <span style="color: orange;">TrackProtect Starter-plan</span></h1>','<h1>What''s in it for you</h1><p>Met dit pakket koopt u 5 registratie credits.</p><p>Dit betekent dat u 5 tracks kunt registreren voor een periode van 1 jaar en u kunt een certificaat downloaden dat speciaal voor u gegenereerd is en een onweerlegbaar bewijs van uw copyright rechten is.');
INSERT INTO `productdesc` (productdesc_id,product_id,locale,title,description) VALUES (3,2,'en-US','<h1 class="productLabel">Thank you for choosing the <span style="color: orange;">TrackProtect Medium-plan</span></h1>','<h1>What''s in it for you</h1><p>With this package you buy 10 registration credits.</p><p>This means you can register 10 tracks for a period of one year and you''ll be able to download a certificate generated specifically for you and your track as proof of registration thus giving you undisputable copyrights.');
INSERT INTO `productdesc` (productdesc_id,product_id,locale,title,description) VALUES (4,2,'nl-NL','<h1 class="productLabel">Thank you for choosing the <span style="color: orange;">TrackProtect Medium-plan</span></h1>','<h1>What''s in it for you</h1><p>Met dit pakket koopt u 10 registratie credits.</p><p>Dit betekent dat u 10 tracks kunt registreren voor een periode van 1 jaar en u kunt een certificaat downloaden dat speciaal voor u gegenereerd is en een onweerlegbaar bewijs van uw copyright rechten is.');
INSERT INTO `productdesc` (productdesc_id,product_id,locale,title,description) VALUES (5,3,'en-US','<h1 class="productLabel">Thank you for choosing the <span style="color: orange;">TrackProtect Pro-plan</span></h1>','<h1>What''s in it for you</h1><p>With this package you buy 15 registration credits.</p><p>This means you can register 15 tracks for a period of one year and you''ll be able to download a certificate generated specifically for you and your track as proof of registration thus giving you undisputable copyrights.');
INSERT INTO `productdesc` (productdesc_id,product_id,locale,title,description) VALUES (6,3,'nl-NL','<h1 class="productLabel">Thank you for choosing the <span style="color: orange;">TrackProtect Pro-plan</span></h1>','<h1>What''s in it for you</h1><p>Met dit pakket koopt u 15 registratie credits.</p><p>Dit betekent dat u 15 tracks kunt registreren voor een periode van 1 jaar en u kunt een certificaat downloaden dat speciaal voor u gegenereerd is en een onweerlegbaar bewijs van uw copyright rechten is.');
INSERT INTO `productdesc` (productdesc_id,product_id,locale,title,description) VALUES (7,4,'en-US','<h1 class="productLabel">Thank you for choosing the <span style="color: orange;">TrackProtect Medium-plan</span></h1>','<h1>What''s in it for you</h1><p>With this package you buy 20 registration credits.</p><p>This means you can register 20 tracks for a period of one year and you''ll be able to download a certificate generated specifically for you and your track as proof of registration thus giving you undisputable copyrights.');
INSERT INTO `productdesc` (productdesc_id,product_id,locale,title,description) VALUES (8,4,'nl-NL','<h1 class="productLabel">Thank you for choosing the <span style="color: orange;">TrackProtect Medium-plan</span></h1>','<h1>What''s in it for you</h1><p>Met dit pakket koopt u 20 registratie credits.</p><p>Dit betekent dat u 20 tracks kunt registreren voor een periode van 1 jaar en u kunt een certificaat downloaden dat speciaal voor u gegenereerd is en een onweerlegbaar bewijs van uw copyright rechten is.');
