// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TrackProtect.Member {
	
	
	public partial class RegisterClientInfo {
		
		protected System.Web.UI.WebControls.Content HeaderContent;
		
		protected System.Web.UI.WebControls.Content BodyContent;
		
		protected System.Web.UI.WebControls.Literal ErrorMessage;
		
		protected System.Web.UI.WebControls.TextBox FirstName;
		
		protected System.Web.UI.WebControls.TextBox LastName;
		
		protected System.Web.UI.WebControls.TextBox AddressLine1;
		
		protected System.Web.UI.WebControls.TextBox AddressLine2;
		
		protected System.Web.UI.WebControls.TextBox Zipcode;
		
		protected System.Web.UI.WebControls.TextBox City;
		
		protected System.Web.UI.WebControls.TextBox State;
		
		protected System.Web.UI.WebControls.DropDownList Country;
		
		protected System.Web.UI.WebControls.TextBox Telephone;
		
		protected System.Web.UI.WebControls.TextBox Cellular;
		
		protected System.Web.UI.WebControls.TextBox AccountOwner;
		
		protected System.Web.UI.WebControls.TextBox TwitterID;
		
		protected System.Web.UI.WebControls.TextBox FacebookID;
		
		protected System.Web.UI.WebControls.DropDownList OwnerKind;
		
		protected System.Web.UI.WebControls.TextBox BillingName;
		
		protected System.Web.UI.WebControls.TextBox SignUpDate;
		
		protected System.Web.UI.WebControls.DropDownList SubscriptionPlah;
		
		protected System.Web.UI.WebControls.TextBox CreditCardNr;
		
		protected System.Web.UI.WebControls.TextBox CVVNr;
		
		protected System.Web.UI.WebControls.TextBox EmailForReceipt;
		
		protected System.Web.UI.WebControls.TextBox Referer;
		
		protected System.Web.UI.WebControls.CheckBox Agreement;
		
		protected System.Web.UI.WebControls.CheckBox Owner;
		
		protected System.Web.UI.WebControls.ImageButton SubmitButton;
		
		protected System.Web.UI.WebControls.Image OnScreenSep;
	}
}
