<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
</head>
<body>
<p></p>
<h1 class="headerLine">About us</h1>
<div class="leftColumn">
<p>Trackprotect is a RHOS Initiative, inspired by Robin Hood of
Sound, supported by RHOS Movement. <br>
After more then a century of a monopolized music industry Robin Hood of
Sound, a.k.a. <br>
Rhos decided it is time for change. Rhos designed a music eco framework
which will change the music industry landscape for good,<br>
enable artists to make a fair buck and the fans to enjoy their artistic
creations without being criminalized.<br>
Now, after almost three years of hard work, Rhos has enabled us to
present to you trackprotect.com. <br>
Trackprotect.com is just one of the first stages of revolutionizing the
music industry...&nbsp;</p>
<p>The launch of trackprotect.com has triggered a chain of events
that can no longer be stopped. <br>
Be advised, we're coming! <br>
<!-- Codes by Quackit.com -->
<script type="text/javascript">
// Popup window code
function newPopup(url) {
popupWindow = window.open(
url,'popUpWindow','height=700,width=800,left=10,top=10,resizable=yes,scrollbars=yes,toolbar=yes,menubar=no,location=no,directories=no,status=yes')
}
</script><a style="color: black;"
 href="JavaScript:newPopup('http://www.rhosmovement.com/about-rhos');"><br>
More about RHOS Movement...</a></p>
</div>
</body>
</html>
