<div class="row">
  <div class="large-6 columns">
    <img src="../Images/logo-footer.png" alt="TrackProtect Logo" />
    <p class="tagline">
      bescherm en dell de waarde van je muzikale werk
    </p>
  </div>
  <div class="large-6 columns">
    <ul class="social-nav">
      <li>
        <a class="social" href="http://www.facebook.com/trackprotect" target="_blank">f</a>
      </li>
      <li>
        <a class="social" href="http://twitter.com/trackprot" target="_blank">l</a>
      </li>
      <li>
        <a class="social" href="http://www.soundcloud.com/trackprotect" target="_blank">!</a>
      </li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <p class="copyright">
      Trackprotect is part of <a href="http://www.soundframework.com">Sound Framework</a>. All rights reserved
    </p>
  </div>
</div>
<div id="back-top">
  <a class="button circle" href="#top">
    <i class="foundicon-up-arrow"></i>
  </a>
</div>