<div class="row">
  <div class="large-12 columns">
    <div class="section-title center">
      <h1>
        ADVANTAGES
      </h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="large-4 columns">
    <div id="benefit-protect">
    </div>
    <h2>
      COPYRIGHT PROTECTED SIMPLE AND AFFORDABLE
    </h2>
  </div>
  <div class="large-4 columns">
    <div id="benefit-cloud">
    </div>
    <h2>
      ALL YOUR PRODUCTIONS IN ONE ONLINE ARCHIVE
    </h2>
  </div>
  <div class="large-4 columns">
    <div id="benefit-social">
    </div>
    <h2>
      FREE SOCIAL MEDIA AND NETWORKING TOOLS
    </h2>
  </div>
</div>