<h3>
  RHOS Initiatives & Sound Framework
</h3>
<p>
  Track and Protect is a RHOS Initiative is part of Sound Framework.
</p>
<p>
  Sound Framework is the basis for the new music industry with transparency,
  fun and a new way of making money with music central.
</p>
<p>
  The coming months will see a number RHOS Initiatives to the public presented.
</p>
<h3>
  A healthy music industry
</h3>
<p>
  A healthy music industry after creation begins with registration, and you do that easily
  and affordable with Track Protect.
</p>
<h3>
  Music allow
</h3>
<p>
  Track Protect is just one of the steps in the revolution for a new music industry.
</p>
<p>
  The launch of Track Protect has a series of events in motion that put
  not to stop.
</p>
<p>
  <em>Be warned, here we come!</em>
</p>
