<div class="large-12 columns">
  <div class="row">
    <div class="large-6 push-6 columns">
      <div id="track">
        <i class="track"></i>
      </div>
      <div id="arrow-1" class="hide-for-small">
        <i class="arrow-1"></i>
      </div>
    </div>
    <div class="large-6 pull-6 columns right-align">
      <article>
        <header>
          <h2>SHARE YOUR MUSIC</h2>
        </header>
        <section>
          <p>Your music's succes is linked to sharing it. The internet plays an essential role in this process, but it also poses a problem. How do you share your music, without just giving away? Trackprotect helps you with that.</p>
          <section>
        </article>
    </div>
  </div>
  <div class="row hide-for-small">
    <div class="large-12 columns">
      <div id="vault">
        <i class="vault"></i>
      </div>
      <div id="arrow-2" class="hide-for-small">
        <i class="arrow-2"></i>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="large-5 push-7 columns">
      <div id="lock">
        <i class="lock"></i>
      </div>
      <div id="arrow-3" class="hide-for-small">
        <i class="arrow-3"></i>
      </div>
    </div>
    <div class="large-7 pull-5 columns article-align">
      <article>
        <header>
          <h2>A DIGITAL VAULT AND CERTIFICATE</h2>
        </header>
        <section>
          <p>Trackprotect helps you prove the point in time your music existed. That helps you to prove your copyright and ownership. This information is processed into a digital certificate and stored in your digital vault.</p>
          <section>
        </article>
    </div>
  </div>
  <div class="row">
    <div class="large-7 columns">
      <div id="network">
        <img src="images/infographic-network.png" alt="infographic network">
            </div>
      <div id="arrow-4" class="hide-for-small">
        <i class="arrow-4"></i>
      </div>
    </div>
    <div class="large-5 columns article-align">
      <article>
        <header>
          <h2>MUSIC NETWORKING TOOLS</h2>
        </header>
        <section>
          <p>Music is rarely created by yourself. With Trackprotect you can easily invite people you have created with or will in the future! Invite each other and protect tracks together!</p>
          <section>
        </article>
    </div>
  </div>

  <div class="row">
    <div class="large-6 push-6 columns">
      <div id="share">
        <img src="images/infographic-share.png" alt="infographic share">
                        </div>
      <div id="arrow-5" class="hide-for-small">
        <i class="arrow-5"></i>
      </div>
    </div>
    <div class="large-6 pull-6 columns article-align">
      <article>
        <header>
          <h2>SOCIAL MEDIA TOOLS</h2>
        </header>
        <section>
          <p>Want to share your protected tracks safely and automated to Soundcloud, Facebook and Twitter? You can, with a push of a button! Trackprotect will take care of that.</p>
          <section>
                    </article>

    </div>

  </div>

  <div class="row">
    <div class="large-7 push-5 columns article-align">
      <article>
        <header>
          <h2>MANAGEMENT AGENCIES</h2>
        </header>
        <section>
          <p>You are a musician, so you want to spend as much time as possible creating music. The Trackprotect managed plan has management tools for management agencies that enable you to let your management take care of your Trackprotect account.</p>
          <section>
                    </article>
    </div>
    <div class="large-5 pull-7 columns">
      <a class="button-try button extra-large" href="/Account/Register.aspx">GET IT NOW</a>

    </div>
  </div>
</div>
