
<div class="leftColumn">
<p>
A lot of people started asking us questions about Trackprotect. Here's a summary of those most frequently asked.
Is your question, or answer not in the list? Let us know! Send an email with your question to <a href="mailto:support@trackprotect.com?SUBJECT=I need answers!">support@trackprotect.com</a>.
</p>
<h2>F.A.Q's - Top 10</h2>
<ul class="faqlist">
	<li>
		<span class="question">1. Why should I protect my tracks via TrackProtect?</span>
		<span class="answer">Copyright is an automatic right you get upon creation of your work. The challenge lies in proving when your work existed and with it your copyright. Trackprotect helps you to prove at what point in time your track existed. This establishes when your copyright came into existence.</span>
	</li>
	<li>
		<span class="question">2. Does it cost money to create an account? <br/> </span>
		<span class="answer">No, a TrackProtect account is free of charge. When you start protecting your own tracks you will need credits which are available through the website.</span>
	</li>
	<li>
		<span class="question">3. You have already Buma Stemra and Sena, why yet another service?</span>
		<span class="answer">Buma Stemra and Sena take care of collective collection copyright proceeds. They do not protect your tracks.</span>
	</li>
	<li>
		<span class="question">4. Is Trackprotect the new, or counterpart of, Buma Stemra of Sena?</span>
		<span class="answer">No, Trackprotect provides a service that helps to prove when your track, and therefore your copyright, existed. Trackprotect is not involved in collecting or repartitioning of copyright proceeds. Trackprotect is an add on for copyright holders whn someone uses your tracks without your permission.
		</span>
	</li>
	<li>
		<span class="question">5. What is an ISRC code, and why should I haveit?</span>
		<span class="answer">ISRC code stands for "International Standard Recording Code", and is intended as a 'vehicle registration' for tracks. In the music industry in Holland Sena issues the "license plates"(ISRC codes). It's important to register with Sena if you want to participate in the repartitioning of copyright proceeds that Sena collectively collects.</span>
	</li>
	<li>
		<span class="question">6. What is legal value of protecting my tracks at Trackprotect?</span>
		<span class="answer">The Dutch legislation does not acknowlegde digital certificates. The registration of your tracks provides supportive evidence about you owning the track and having the copyrights to it. Case law shows that a court would weigh what effort a person has made to protect his or her track. Protecting your track with Trackprotect shows that you have put effort into it. You can only get compelling evidence(conclusive evidence) by physically registering your track at a Notary. This is pretty expensive.</span>
	</li>
	<li>
		<span class="question">7. It is mandatory to upload my printed and signed to my account?</span>
		<span class="answer">No, it is not, but it will contribute to the weight of your evidence. The more complete your registration, the  more powerful your evidence in a court of law.</span>
	</li>
	<li>
		<span class="question">8. Why is Trackprotect, in comparison to other services, so affordable?</span>
		<span class="answer">One of the reasons is that Trackprotect protects your track for one year. After a year you can choose to prolong your trackprotection. In most cases this is only possible for a period of 5 years. Another reason is that Trackprotect is a RHOS Initiative, based on the Robin Hood of Sound Sound ideology. An important criterion of RHOS ideology is that music and the industry should be accessible to everyone, so also in terms of pricing.</span>
	</li>
	<li>
		<span class="question">9. What to do if someone used my track without my permission?</span>
		<span class="answer">Track Protect has partnered up with different legal partners to affordably assist TrackProtect users in case of a conflict. These partners have many years of experience in the field of copyright and also support the RHOS ideology. Do you have a problem with one of your tracks? Let us know, we put you in touch with the right partner for you! <a href="mailto:support@trackprotect.com?SUBJECT=I need legal help!">support@trackprotect.com</a></span>
	</li>
	<li>
		<span class="question">10. What is a collaborating artist?</span>
		<span class="answer">A collaborating artist is someone with whom you have made a track, for example, a fellow composer, backing vocalist, a drummer or guitarist.</span>
	</li>
</ul>
<h2>Collective track protection: The Bulk Plan</h2>
<ul class="faqlist">
	<li>
		<span class="question">I represent several artists, I can collectively protect tracks?</span>
		<span class="answer">Yes, we have a management control panel for companies that collectively protect track for several musicians. The management control panel is only available in combination with the bulk plan.
</span>
	</li>
	<li>
		<span class="question">What are the advantages of bulk plan?</span>
		<span class="answer">There are two main reasons to choose the "Bulk Plan" : <ol><li>Register tracks for multiple users from the management control panel</li><li>You buy your credits in bulk for all your related artist which will get you an even better credit rate.</li></ol>
</span>
	</li>
	<li>
		<span class="question">Is the track protected in my name when I de collective protection?</span>
		<span class="answer">Yes, the management control panel is a separate user that registers your track in <b>your</b> account. The system also keeps track which management user registered it for you.</span>
	</li>
	<li>
		<span class="question">Can anybody make any change to or in my registrations?</span>
		<span class="answer">No. After completing a registration it is final. If you would change any single part in the data that was added tot the registration it would cause the digital cerftificate to be invalid. The evidence Trackprotect offers is pinpointing the exact state of information at a certian point in time. The certificate can help proof that nothing in the data has been changed from the point of registration.</span>
	</li>
</ul>
<h2>Social commitment</h2>
<ul class="faqlist">
	<li>
		<span class="question">Does Trackprotect contribute anything to society?</span>
		<span class="answer">Yes, Trackprotect is part of a greater good, the RHOS Movement Music Eco Framework, that strives for a sustainable music industry, accessible to all.</span>
	</li>
	<li>
		<span class="question">What's the connection between Trackprotect and RHOS Movement?</span>
		<span class="answer">Trackprotect is a RHOS Initiative. Concepts by Robin Hood of Sound, <b>enabled</b> by entrepreneurs, supported by the crowd.</span>
	</li>
	<li>
		<span class="question">What's the connection between Trackprotect and the Sustain Sound Foundation?</span>
		<span class="answer">The Sustain Sound Foundation was founded by people that support the RHOS ideology. The foundation has contributed to the development of Trackprotect.</span>
	</li>
	<li>
		<span class="question">I like Trackprotect and RHOS Movement, how can I help?</span>
		<span class="answer">RHOS Movement is revolutionizing the music industry, so we welcome all the help we can get! Just send an email to <a href="mailto:rhos@rhosmovement.com">rhos@rhosmovement.com</a>, Robin Hood of Sound will personally send you a reply!</span>
	</li>
</ul>
<h2>Trackprotect education</h2>
<ul class="faqlist">
	<li>
		<span class="question">Trackprotect and education?</span>
		<span class="answer">Track Protect also contributes to a healthy music industry. The company donates &euro;125.000,- worth of credits to all (music)students in Holland.<a href="/promo.aspx"> Read more...</a></span>
	</li>
	<li>
		<span class="question">How do I become a trackprotect ambassador?</span>
		<span class="answer">Anybody can sign up, but you have to follow a music related education and you have to be the first to sign up! <a href="/promo.aspx"> Read more ...</a></span>
	</li>
</ul>
<h2>General questions about the use of Trackprotect</h2>
<ul class="faqlist">	
	<li>
		<span class="question">How long is my track protected?</span>
		<span class="answer">By default your tracks are protected for 1 year for 1 credit. After this period you can prolong your protection by 1 year.</span>
	</li>
	<li>
		<span class="question">How do I get credits and is purchasing online with Trackprotect secure?</span>
		<span class="answer">You can purchase credits via our website. All payments are processed 100% secure via our payment service provider <a href="http://www.icepay.nl" target="_blank">Icepay</a>.</span>
	</li>
	<li>
		<span class="question">Does Trackprotect also protect sheet music and lyrics?</span>
		<span class="answer">Yes, with every registration you can also upload and protect sheet music and lyrcs. They will be added to the certificate, fortifying your protection.</span>
	</li>
	<li>
		<span class="question">Can I play protected tracks in my account?</span>
		<span class="answer">Yes, playing a protected track is possible but only when you've purchased pro account credits. The player function will remain active as long as the pro account credits are valid, one full year!</span>
	</li>
	<li>
		<span class="question">What to do when I make changes to my track?</span>
		<span class="answer">When you make changes to a track you will need to re-register it. The value of protecting your track is the exact state of your track at the moment of registration. When changes are made, we need to register the changes, and create a new record, with a new certificate.</span>
	</li>
	<li>
		<span class="question">What is the maximum size of the track I'm protecting?</span>
		<span class="answer">The maximum size per registered track is 10 megabytes.</span>
	</li>
	<li>
		<span class="question">Can I register multiple tracks in one go?</span>
		<span class="answer">No, every registration is unique and must therefore be done separately.</span>
	</li>
	<li>
		<span class="question">Can I register one track for more than one year in one go?</span>
		<span class="answer">No, Trackprotect offers registration for one track, for 1 yesr. The Trackprotect system will send you an email reminder when a protectiom is about to expire with the option to prolong protection.</span>
	</li>
	<li>
		<span class="question">What is a collaborating artist?</span>
		<span class="answer">A collaborating artist is someone with whom you have made a track, for example, a fellow composer, backing vocalist, a drummer or guitarist..</span>
	</li>
	<li>
		<span class="question">I can't add a colaborating artist when I protect my track.</span>
		<span class="answer">To add colaborating artists you will first need to have artist relations.</span>
	</li>
	<li>
		<span class="question">How do I add or invite colaborating artists?</span>
		<span class="answer">To add relations to your account you need to log in to your account, go to the control panel, click on relations and enter the email address from the person you would like to add as a relation and click send. The person you are inviting will receive an invitation request asking them to become your partner in music. All they need to do is click the accept link in the email. If the recipient address is a registered Trackprotect user the system will recognize it as such and a relation will be created. If not, he or she will be asked to register to Trackprotect, this regsitration is free of charge. After registration the relation is created and your relation in Trackprotect will be visible in the control panel.</span>
	</li>	
	<li>
		<span class="question">I have created a track with someone, who gets the copyright?</span>
		<span class="answer">When you create a track together you have joint copyright. When you protect a track it will be assigned to the account you are logged in as during registration. The person you have created the track with will be mentioned as a colaborating artist. You can describe the rol of the other party during each regsitration.</span>
	</li>	
	<li>
		<span class="question">I have received an invitation email, what to do? </span>
		<span class="answer">If you know the person sending you the invitation, just click the accept link in the email and the person will be added to your account as a relation. If you don't know the person, or you just don't want to accept, you don't have to do anything.</span>
	</li>
	<li>
		<span class="question">Can other people see my relation with other Trackprotect users?</span>
		<span class="answer">No, this information is only visible to you and your relation.</span>
	</li>
</ul>
<h2>Administratief</h2>
<ul class="faqlist">	
	<li>
		<span class="question">Can my credits expire?</span>
		<span class="answer">Yes, they can. Credits are valid for one full year. During this year they can be used to protect tracks. At the moment a credit is used it offers protection for again, one full year from the moment of protection.</span>
	</li>
	<li>
		<span class="question">Can my account expire?</span>
		<span class="answer">No it will not in most cases, it depends on the activity in your account. When you have active protected tracks in your account, or you are mentioned as a colaborating artist in protected tracks by other users you account will remain active. If not your account will be removed after three months. The system will send you reminders before anything is removed.</span>
	</li>
	<li>
		<span class="question">What happens when my track protection expires?</span>
		<span class="answer">Before expiration of trackprotection you will be notified thru email. This email contains information which track is about to expire. You now have the choice to prolong the trackprotection for that specific track.</span>
	</li>
	<li>
		<span class="question">I recieved an email that my credits and or track(s) are about to expires</span>
		<span class="answer">Your credits and protected tracks are valid for 1 year. Credits have to be used within one year from the moment of purchase. When used each credit protects one track for a year. Credits will expire after one year. Protection of tracks can be prolonged, credits cannot. When you received an email about expiring credits the only thing you can do is protect tracks, that is what they are for!</span>
	</li>
	<li>
		<span class="question">Why do credits expire?</span>
		<span class="answer">When designing the The Trackprotect service we had two options, charge our users a monthly fee, or go for the expiring credits option. We like to keep our systems updated and clean, we would not like to get stuck with 3 year old accounts with no protected tracks. Accounts like this would harm purpose of Trackprotect in the Musc Eco Framework, data should be current and relevant to the framework.</span>
	</li>
	<li>
		<span class="question">Ik heb betaald, en mijn credits zijn niet aan mijn account toegevoegd</span>
		<span class="answer">Neem in dit geval zo spoedig mogelijk contact op met <a href="mailto:support@trackprotect.com">support@trackprotect.com</a></span>
	</li>
</ul>
<h2>Privacy</h2>
<ul class="faqlist">	
	<li>
		<span class="question">Does Trackprotect share my information wit other companies/parties?</span>
		<span class="answer">Nee, Trackprotect woulkd never share you information with any third party without your consent.</span>
	</li>
	<li>
		<span class="question">Can other people acces my tracks or information?</span>
		<span class="answer">No. Absolutely not.</span>
	</li>
	<li>
		<span class="question">What happens to my data when I close my account?</span>
		<span class="answer">When you close your account all your data, including your protected tracks will be erased from our systems.</span>
	</li>
</ul>
<h2>Data en veiligheid</h2>
<ul class="faqlist">	
	<li>
		<span class="question">Where are my tracks stored?</span>
		<span class="answer">Your protected tracks and digital certificates are stored on Trackprotect&rsquo;s secure servers.</span>
	</li>
	<li>
		<span class="question">Are the Trackprotect servers secure?</span>
		<span class="answer">The Trackprotect servers are hosted in a secure data center. The servers are properly backupped and managed by qualified professional system administrators.</span>
	</li>
</ul>
<!--
<h2></h2>
<ul class="faqlist">	

</ul>
-->
</div>