<div class="section-title center">
  <h1>
    F.A.Q
  </h1>
</div>

<div class="row">
  <div class="large-6 columns">
    <ul class="no-style">
      <li>
        <h3>
          <span class="question">1. Why should I protect my tracks via Track Protect? </span>
        </h3>
        <p>
          <span class="answer">
            Why should I protect my tracks via Track Protect? If you have a
            track makes you automatically copyright. It is often difficult to prove when something
            you have created. Track ProtectTools helps you prove when your track existed. If
            that can be established is at least talk of copyright from that time.
          </span>
        </p>
      </li>
      <li>
        <h3>
          <span class="question">2. Does it cost money to create an account? </span>
        </h3>
        <p>
          <span class="answer">
            No, create an account with Track Protect is free. Only when you
            track captures you credits, which are available via the website.
          </span>
        </p>
      </li>
      <li>
        <h3>
          <span class="question">
            3. You have already Buma Stemra and Sena, why yet another service?
          </span>
        </h3>
        <p>
          <span class="answer">
            Buma Stemra and Sena are there to collectively copyrighted to collect
            and distribute. They are not about protecting your work.
          </span>
        </p>
      </li>
      <li>
        <h3>
          <span class="question">
            4. Protect the track is new, or counterpart, Buma Stemra or Sena?
          </span>
        </h3>
        <p>
          <span class="answer">
            No. Track ProtectTools provides a service that helps you to prove
            your copyright. Track Protect is not involved in collecting or distributing your
            copyright apply. Track Protect is an addition to copyright holders in the event
            that other unauthorized use of their tracks.
          </span>
        </p>
      </li>
      <li>
        <h3>
          <span class="question">5. What is an ISRC code, and why should I do that? </span>
        </h3>
        <p>
          <span class="answer">
            ISRC code stands for "International Standard Recording Code", and
            is intended as a kind of 'licensing' for tracks. The Sena gives the badges (ISRC
            codes) from. It is therefore important to register with the Sena, then divide them
            into the distribution of collective author collected funds.
          </span>
        </p>
      </li>
    </ul>
  </div>
  <div class="large-6 columns">
    <ul class="no-style">
      <li>
        <h3>
          <span class="question">6. What legal value recording my tracks? </span>
        </h3>
        <p>
          <span class="answer">
            The Dutch legislation does not provide digital certificates. The
            registration of your tracks provides corroborating evidence. If you end up in a
            legal dispute over supports your claim that a track is yours, and that you are the
            copyright holder. A judge will in many cases see what someone has done to his right
            to protect. Your track record shows that you have made an effort for you there.
            Compelling evidence (indisputable evidence) you can only get through a deposit deed
            at the notary.
          </span>
        </p>
      </li>
      <li>
        <h3>
          <span class="question">
            7. Is it compulsory to sign my account information in your possession?
          </span>
        </h3>
        <p>
          <span class="answer">
            No, it is not mandatory, but it does contribute to the weight of
            your evidence. So how you complete your account registration does, the more powerful
            your evidence.
          </span>
        </p>
      </li>
      <li>
        <h3>
          <span class="question">
            8. How can protect my track by track Protect it affordable?
          </span>
        </h3>
        <p>
          <span class="answer">
            One of the reasons is that Track Protect your track for a year
            captures. In many cases, only 5 years. Another reason is because one RHOS Protect
            Track Initiative is based on the Robin Hood of Sound ideas. An important criterion
            of the RHOS ideas is that it should be accessible to everyone, including in terms
            of pricing.
          </span>
        </p>
      </li>
      <li>
        <h3>
          <span class="question">
            9. Who can I contact someone without my permission my track used?
          </span>
        </h3>
        <p>
          <span class="answer">
            Track Protect has several legal partners with which arrangements
            have been made to track users Protect payable to assist in the event of a conflict.
            These partners have years of experience in the field of copyright and also support
            the RHOS ideas. Got a problem with one of your tracks? Let us know, we'll bring
            you in contact with the right party! <a href="mailto:support@trackprotect.com?SUBJECT=Ik have legal help nodig!">
              support@trackprotect.com
            </a>
          </span>
        </p>
      </li>
      <li>
        <h3>
          <span class="question">10. What is a collaborating artist? </span>
        </h3>
        <p>
          <span class="answer">
            A cooperating artist is someone with whom you have made a track,
            for example, a fellow composer, background singer, drummer and guitarist.
          </span>
        </p>
      </li>
    </ul>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <a class="right" href="FAQ.aspx">Click to see all &lt;&lt;</a>
  </div>
</div>