<p>
  <h1 class="headerLine">How it works</h1>
</p>
<div class="leftColumn">
  <!--<img src="images/guitarguy.jpg" width="100%" align="right">-->
  <p>
    Trackprotect is a music copyright protection service.
  </p>
  <p>
    The era of internet, digital music and social media forces musicians more then ever to share their music as much as possible in order to be succesful.
    They do so for personal use or promotional puproses.
  </p>
  <p>
    But what happens when someone (re)uses your track for commercial purposes? How do you how do you prove that your work is yours?
  </p>
  <h3>
    <b>A Digital vault and certificate</b>
  </h3>
  When you protect a track a digital certificate is generated.
  The certificate contains information about the date and time stamp of the registration.
  This helps you to prove when your work existed and with it your copyright.
  </p>

  <p>
    <h3>
      <b>Your musician relations managed</b>
    </h3>
    In a lot of cases music is created with other people. In Trackprotect you can manage musicians the you have worked with. Just invite each other and protect tracks together!
  </p>
  <p>
    <h3>
      <b>Protecting tracks</b>
    </h3>
    <p>
      To start protecting tracks you will need credits. Protecting a track costs 1 credit for 1 year. During this year your track is secured in your account.
      After registering a track you will also receive a proof of registration certificate for your administration.
    </p>
    <p>
      <h3>
        <b>Your benefit :</b>
      </h3>
      <br>
        <ol>
          <li>Your copyright protected, fast, easy and affordable</li>
          <li>Your productions in one secure online archive</li>
          <li>Your relations with cooperating musicians easily managed and registered</li>
        </ol>
      </p>
    <br>

      <h3>
        <b>Sign up!</b>
      </h3>
      <p>
        Trackprotect is effective, easy to use and cost effective.
        Creating an account is free of charge!
      </p>

      <p>
        <strong>
          <i>
            So, now you know how it works... <br>What are you waiting for?</strong>
        </i>
      </p>
      <p>
        <br>
          <!--<a href="http://www.trackprotect.com/Account/Register.aspx"><img src="/images/btn_signup.png"></a>-->
          <a href="/Account/Register.aspx">
            <img src="/images/btn_signup.png">
  </a>
        </p>
    </div>